### PR TITLE
Parse object detection inference and draw bounding boxes

### PR DESCRIPTION
**Pull request by gheinrich**
Add task to call `infer.py` during single or multiple-image inference. This produces output like:
detector-bboxes

I had to make a small change over https://github.com/ajtao/digits-detector/pull/28/commits/4b178fd162fff270638bb8e638c94cc94d01a3c0 to make specification of `val-path` optional.

### CODE REVIEW

**Comment by gheinrich** [comment]
There are cases when I feel the detector is doing pretty well too (even with mAP<25%), for example:
detector-bboxes-2

**Comment by gheinrich** [comment]
Rebased on tip of `gtc-demo` branch

**Comment by lukeyeager** [comment]
Oh thanks! Sorry, my rebasing is annoying sometimes. I had just cherry-picked your commit.

**Comment by gheinrich** [comment]
Yes that's why I mentioned I had to make a small change on top of https://github.com/ajtao/digits-detector/pull/28/commits/4b178fd162fff270638bb8e638c94cc94d01a3c0 to make `val-path` optional (I don't see why we'd need it for inference): https://github.com/gheinrich/digits-detector/commit/29bde6c772bffa7cbb7617d8072b1c933ed64718

**Comment by lukeyeager** [comment]
It's working! The visualizations and statistics are gone though :(

I'll wait to merge this until we get the `val-path` thing sorted out.

**Comment by gheinrich** [comment]
I can re-instate visualizations (maybe in another commit?). That should be quite straightforward (we can create two tasks: `InferenceTask` + `ObjectDetectionInferenceTask`) and have the `InferenceJob` pick the appropriate information from each before returning results to the `infer_one` view.

**Comment by lukeyeager** [comment]
Haha yeah that's probably what we ought to do. Pretty sad that we'll end up running inference on the same image twice, but what are you going to do?

**Comment by gheinrich** [comment]
In a cleaner implementation it shouldn't be too difficult to isolate the code that takes the network output and returns bounding boxes. And have this code run in DIGITS (in a similar way to how we currently create confusion matrices). But maybe this is a task we wish to defer to a later day, when things have become more stable in the detector.

**Comment by lukeyeager** [comment]
For the next release, we're planning to have clustering and mAP calculation all in-network. So most of what we're doing right now won't be needed.

**Pull request merged**
